// Degraded-thumbnail cache for the GUI, SHARED with ExtendDB.
//
//   • Same on-disk directory  : <LB>\Plugins\ExtendDB\cache\thumbs (created even if
//     ExtendDB isn't installed — no code change needed in ExtendDB).
//   • Same KEY algorithm      : byte-identical to ExtendDB.Web.Theme.ThumbCache.KeyFor,
//     so a thumb generated by either side is a cache HIT for the other (when the
//     SOURCE file path matches — which it does when both resolve via GameCache).
//   • Same output             : JPEG q72 (keepAlpha=false) / WebP q82 w/ alpha
//     (keepAlpha=true, used for clear logos). "WxH>" = shrink-to-fit, never upscale.
//
// Magick is an optional dependency: a cache HIT returns the file with no Magick at
// all; only a MISS needs Magick to generate (Decode/Generate is isolated so a missing
// Magick.NET — standalone, no ExtendDB — is caught and the call returns null).
//
// MagickSupport.Init mirrors ExtendDB's Utils.InstallDlls for the native lib: it
// deploys the bundled Magick.Native-Q16-x64.dll.api (next to the exe) to
// <LB>\ThirdParty\ExtendDB\Magick.Native-Q16-x64.dll if absent and points the DLL
// search path there, so LiteBox works WITH or WITHOUT ExtendDB loaded.

using System;
using System.Collections.Concurrent;
using System.IO;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;
using System.Threading;
using System.Threading.Tasks;

namespace LbApiHost.Host.Media;

internal static class MagickSupport
{
    [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    private static extern bool SetDllDirectory(string lpPathName);

    /// <summary>Deploy the bundled native ImageMagick lib to ExtendDB's ThirdParty
    /// folder (if not already there) and add it to the DLL search path. Idempotent;
    /// safe to call before ExtendDB (which does the same thing) loads.</summary>
    public static void Init(string lbRoot)
    {
        try
        {
            // Magick.Native-Q16-x64.dll is deployed by NativeInstaller (embedded → ThirdParty\ExtendDB);
            // here we only add that folder to the native search path.
            string nativeDir = Path.Combine(lbRoot, "ThirdParty", "ExtendDB");
            Directory.CreateDirectory(nativeDir);
            SetDllDirectory(nativeDir);   // one slot; ExtendDB sets the same dir later — no conflict
        }
        catch { }
    }
}

internal static class ThumbCache
{
    /// <summary>Longest-edge of the degraded thumbnail (px). MUST match ExtendDB's.</summary>
    public const int DefaultMaxDim = 360;

    private static string _dir;

    /// <summary>Point the cache at the shared ExtendDB thumbs dir (created on demand).</summary>
    public static void Init(string lbRoot)
        => _dir = Path.Combine(lbRoot, "Plugins", "ExtendDB", "cache", "thumbs");

    /// <summary>The shared thumbs directory, created on demand. Video thumbnails (see
    /// Host.Video.VideoThumbnailer) land here too: same folder, same 360 px / JPEG convention — only the KEY
    /// differs (a video also keys on mtime, since replacing one must re-extract the frame).</summary>
    public static string Folder => Dir;

    private static string Dir
    {
        get
        {
            // Normal path is the shared ExtendDB thumbs dir (set in Init). The fallback (no LB / Init not
            // called) goes under Core\litebox\ like everything else LiteBox creates — never loose in Core.
            var d = _dir ?? Path.Combine(LiteBoxPaths.Data, "thumbs");
            try { Directory.CreateDirectory(d); } catch { }
            return d;
        }
    }

    /// <summary>Path of a cached resized thumbnail for <paramref name="sourcePath"/>,
    /// generating it synchronously on first use. keepAlpha=true → WebP w/ alpha (clear
    /// logos); false → JPEG. Returns null on any failure (caller serves the original).
    /// A cache HIT needs no Magick; a MISS needs Magick (else returns null).</summary>
    public static string GetOrCreate(string sourcePath, int maxDim = DefaultMaxDim, bool keepAlpha = false)
    {
        var target = TargetFor(sourcePath, maxDim, keepAlpha);
        if (target == null) return null;
        if (File.Exists(target)) return target;        // shared cache HIT — no Magick needed
        try { return Generate(sourcePath, target, maxDim, keepAlpha); }
        catch { return null; }                          // missing Magick (standalone) → null
    }

    /// <summary>Cached thumbnail path if it ALREADY exists, else null. Never runs
    /// Magick — instant, safe in a hot UI path.</summary>
    public static string GetCachedOnly(string sourcePath, int maxDim = DefaultMaxDim, bool keepAlpha = false)
    {
        var target = TargetFor(sourcePath, maxDim, keepAlpha);
        return (target != null && File.Exists(target)) ? target : null;
    }

    // ── Async generation queue ───────────────────────────────────────────────
    // On a MISS the UI shows the full original immediately and enqueues the thumb
    // here, so it exists (HIT) next time without ever blocking the display. Dedup
    // by target path; bounded concurrency so a fast browse doesn't saturate the CPU.
    private static readonly ConcurrentDictionary<string, byte> _pending = new(StringComparer.OrdinalIgnoreCase);
    private static readonly SemaphoreSlim _gate = new(Math.Max(1, Environment.ProcessorCount / 2));

    /// <summary>Queue background generation of a thumbnail (no-op if it already
    /// exists or is already queued). Fire-and-forget; never throws.</summary>
    public static void EnqueueGenerate(string sourcePath, int maxDim = DefaultMaxDim, bool keepAlpha = false)
    {
        var target = TargetFor(sourcePath, maxDim, keepAlpha);
        if (target == null || File.Exists(target)) return;
        if (!_pending.TryAdd(target, 0)) return;        // already generating/queued
        _ = Task.Run(async () =>
        {
            await _gate.WaitAsync().ConfigureAwait(false);
            try { if (!File.Exists(target)) Generate(sourcePath, target, maxDim, keepAlpha); }
            catch { }
            finally { _gate.Release(); _pending.TryRemove(target, out _); }
        });
    }

    // Resolve the on-disk thumbnail path (size-versioned key); null if the source
    // is missing/unreadable. No Magick, no generation.
    private static string TargetFor(string sourcePath, int maxDim, bool keepAlpha)
    {
        if (string.IsNullOrEmpty(sourcePath)) return null;
        long size;
        try { var fi = new FileInfo(sourcePath); if (!fi.Exists) return null; size = fi.Length; }
        catch { return null; }
        try { return Path.Combine(Dir, KeyFor(sourcePath, size, maxDim, keepAlpha) + (keepAlpha ? ".webp" : ".jpg")); }
        catch { return null; }
    }

    // Isolated so the JIT-time assembly-not-found (Magick absent) is caught by GetOrCreate.
    private static string Generate(string sourcePath, string target, int maxDim, bool keepAlpha)
    {
        var tmp = target + "." + Guid.NewGuid().ToString("N") + ".tmp";
        using (var img = new ImageMagick.MagickImage(sourcePath))
        {
            img.Thumbnail(new ImageMagick.MagickGeometry($"{maxDim}x{maxDim}>"));  // shrink-to-fit only
            if (keepAlpha) { img.Format = ImageMagick.MagickFormat.WebP; img.Quality = 82; }
            else { img.Format = ImageMagick.MagickFormat.Jpeg; img.Quality = 72; }
            img.Strip();
            img.Write(tmp);
        }
        try { File.Move(tmp, target, overwrite: false); }
        catch { try { File.Delete(tmp); } catch { } }
        return File.Exists(target) ? target : null;
    }

    // Byte-identical to ExtendDB.Web.Theme.ThumbCache.KeyFor — do NOT change.
    private static string KeyFor(string sourcePath, long size, int maxDim, bool keepAlpha)
    {
        var seed = (sourcePath.ToLowerInvariant()) + "|" + size + "|" + maxDim + "|" + (keepAlpha ? "a" : "o");
        byte[] hash = SHA1.HashData(Encoding.UTF8.GetBytes(seed));
        var sb = new StringBuilder(24);
        for (int i = 0; i < 8; i++) sb.Append(hash[i].ToString("x2")); // 16 hex chars
        sb.Append('_').Append(size).Append('_').Append(maxDim).Append(keepAlpha ? "a" : "");
        return sb.ToString();
    }
}
