// Degraded-thumbnail cache for the GUI, SHARED with ExtendDB.
//
//   • Same on-disk directory  : <LB>\Plugins\ExtendDB\cache\thumbs (created even if
//     ExtendDB isn't installed — no code change needed in ExtendDB).
//   • Same KEY algorithm      : byte-identical to ExtendDB.Web.Theme.ThumbCache.KeyFor,
//     so a thumb generated by either side is a cache HIT for the other (when the
//     SOURCE file path matches — which it does when both resolve via GameCache).
//   • Same output             : JPEG q72 (keepAlpha=false) / WebP q82 w/ alpha
//     (keepAlpha=true, used for clear logos). "WxH>" = shrink-to-fit, never upscale.
//
// Magick is an optional dependency: a cache HIT returns the file with no Magick at
// all; only a MISS needs Magick to generate (Decode/Generate is isolated so a missing
// Magick.NET — standalone, no ExtendDB — is caught and the call returns null).
//
// MagickSupport.Init mirrors ExtendDB's Utils.InstallDlls for the native lib: it
// deploys the bundled Magick.Native-Q16-x64.dll.api (next to the exe) to
// <LB>\ThirdParty\ExtendDB\Magick.Native-Q16-x64.dll if absent and points the DLL
// search path there, so LiteBox works WITH or WITHOUT ExtendDB loaded.

using System;
using System.IO;
using System.Runtime.InteropServices;
using System.Security.Cryptography;
using System.Text;

namespace LbApiHost.Host.Media;

internal static class MagickSupport
{
    [DllImport("kernel32.dll", CharSet = CharSet.Unicode, SetLastError = true)]
    private static extern bool SetDllDirectory(string lpPathName);

    /// <summary>Deploy the bundled native ImageMagick lib to ExtendDB's ThirdParty
    /// folder (if not already there) and add it to the DLL search path. Idempotent;
    /// safe to call before ExtendDB (which does the same thing) loads.</summary>
    public static void Init(string lbRoot)
    {
        try
        {
            string nativeDir = Path.Combine(lbRoot, "ThirdParty", "ExtendDB");
            Directory.CreateDirectory(nativeDir);
            string target = Path.Combine(nativeDir, "Magick.Native-Q16-x64.dll");
            if (!File.Exists(target))
            {
                string src = Path.Combine(AppContext.BaseDirectory, "Magick.Native-Q16-x64.dll.api");
                if (File.Exists(src)) { try { File.Copy(src, target); } catch { } }
            }
            SetDllDirectory(nativeDir);   // one slot; ExtendDB sets the same dir later — no conflict
        }
        catch { }
    }
}

internal static class ThumbCache
{
    /// <summary>Longest-edge of the degraded thumbnail (px). MUST match ExtendDB's.</summary>
    public const int DefaultMaxDim = 360;

    private static string _dir;

    /// <summary>Point the cache at the shared ExtendDB thumbs dir (created on demand).</summary>
    public static void Init(string lbRoot)
        => _dir = Path.Combine(lbRoot, "Plugins", "ExtendDB", "cache", "thumbs");

    private static string Dir
    {
        get
        {
            var d = _dir ?? Path.Combine(AppContext.BaseDirectory, "cache", "thumbs");
            try { Directory.CreateDirectory(d); } catch { }
            return d;
        }
    }

    /// <summary>Path of a cached resized thumbnail for <paramref name="sourcePath"/>,
    /// generating it on first use. keepAlpha=true → WebP w/ alpha (clear logos);
    /// false → JPEG. Returns null on any failure (caller serves the original).
    /// A cache HIT needs no Magick; a MISS needs Magick (else returns null).</summary>
    public static string GetOrCreate(string sourcePath, int maxDim = DefaultMaxDim, bool keepAlpha = false)
    {
        if (string.IsNullOrEmpty(sourcePath)) return null;
        long size;
        try { var fi = new FileInfo(sourcePath); if (!fi.Exists) return null; size = fi.Length; }
        catch { return null; }

        string ext = keepAlpha ? ".webp" : ".jpg";
        string target;
        try { target = Path.Combine(Dir, KeyFor(sourcePath, size, maxDim, keepAlpha) + ext); }
        catch { return null; }

        if (File.Exists(target)) return target;       // shared cache HIT — no Magick needed

        try { return Generate(sourcePath, target, maxDim, keepAlpha); }
        catch { return null; }                          // missing Magick (standalone) → null
    }

    // Isolated so the JIT-time assembly-not-found (Magick absent) is caught by GetOrCreate.
    private static string Generate(string sourcePath, string target, int maxDim, bool keepAlpha)
    {
        var tmp = target + "." + Guid.NewGuid().ToString("N") + ".tmp";
        using (var img = new ImageMagick.MagickImage(sourcePath))
        {
            img.Thumbnail(new ImageMagick.MagickGeometry($"{maxDim}x{maxDim}>"));  // shrink-to-fit only
            if (keepAlpha) { img.Format = ImageMagick.MagickFormat.WebP; img.Quality = 82; }
            else { img.Format = ImageMagick.MagickFormat.Jpeg; img.Quality = 72; }
            img.Strip();
            img.Write(tmp);
        }
        try { File.Move(tmp, target, overwrite: false); }
        catch { try { File.Delete(tmp); } catch { } }
        return File.Exists(target) ? target : null;
    }

    // Byte-identical to ExtendDB.Web.Theme.ThumbCache.KeyFor — do NOT change.
    private static string KeyFor(string sourcePath, long size, int maxDim, bool keepAlpha)
    {
        var seed = (sourcePath.ToLowerInvariant()) + "|" + size + "|" + maxDim + "|" + (keepAlpha ? "a" : "o");
        byte[] hash = SHA1.HashData(Encoding.UTF8.GetBytes(seed));
        var sb = new StringBuilder(24);
        for (int i = 0; i < 8; i++) sb.Append(hash[i].ToString("x2")); // 16 hex chars
        sb.Append('_').Append(size).Append('_').Append(maxDim).Append(keepAlpha ? "a" : "");
        return sb.ToString();
    }
}
