// EmuMovies ↔ LaunchBox mapping tables — REFERENCE DATA (not algorithm), lifted from the offline
// scraper's appsettings.json (scrapper-project/EmuMoviesDownloader) that builds the extended DB's
// emumovies rows. These are just naming facts: EmuMovies platform/media-type/region vocabulary vs
// LaunchBox's. Regenerate from that config if EmuMovies adds systems/types.
//
// A LaunchBox platform maps to an ORDERED LIST of EmuMovies platforms: the resolver tries them in order and
// stops at the first that yields any media for the game (see EmuMoviesCatalog.ResolveForGameAsync). Most are
// a single entry; e.g. Arcade tries "Arcade" then "ArcadePC".
//
// AUTO-GENERATED — do not hand-edit; re-run the generator against appsettings.json.

#nullable enable

using System;
using System.Collections.Generic;

namespace LbApiHost.Host.Integrations;

internal static class EmuMoviesMaps
{
    /// <summary>LaunchBox platform name → ordered EmuMovies platform names (tried in order). Missing ⇒ unsupported.</summary>
    public static readonly IReadOnlyDictionary<string, string[]> Platform = new Dictionary<string, string[]>(StringComparer.OrdinalIgnoreCase)
    {
        ["3DO Interactive Multiplayer"] = new[] { "Panasonic_3DO" },
        ["Acorn Archimedes"] = new[] { "Acorn_Archimedes" },
        ["Acorn Atom"] = new[] { "Acorn_Atom" },
        ["Acorn Electron"] = new[] { "Acorn_Electron" },
        ["Amstrad CPC"] = new[] { "Amstrad_CPC" },
        ["Amstrad GX4000"] = new[] { "Amstrad_GX4000" },
        ["APF Imagination Machine"] = new[] { "APF_Imagination_Machine" },
        ["Apogee BK-01"] = new[] { "Apogee_BK-01" },
        ["Apple II"] = new[] { "Apple_II" },
        ["Apple IIGS"] = new[] { "Apple_IIGS" },
        ["Apple Mac OS"] = new[] { "Apple_Macintosh" },
        ["Arcade"] = new[] { "Arcade", "ArcadePC" },
        ["Atari 2600"] = new[] { "Atari_2600" },
        ["Atari 5200"] = new[] { "Atari_5200" },
        ["Atari 7800"] = new[] { "Atari_7800" },
        ["Atari 800"] = new[] { "Atari_8_bit" },
        ["Atari Jaguar"] = new[] { "Atari_Jaguar" },
        ["Atari Jaguar CD"] = new[] { "Atari_Jaguar_CD" },
        ["Atari Lynx"] = new[] { "Atari_Lynx" },
        ["Atari ST"] = new[] { "Atari_ST" },
        ["Atari XEGS"] = new[] { "Atari_XEGS" },
        ["Bally Astrocade"] = new[] { "Bally_Astrocade" },
        ["BBC Microcomputer System"] = new[] { "Acorn_BBC_Micro" },
        ["Camputers Lynx"] = new[] { "Camputers_Lynx" },
        ["Casio Loopy"] = new[] { "Casio_Loopy" },
        ["Casio PV-1000"] = new[] { "Casio_PV_1000" },
        ["Coleco ADAM"] = new[] { "Coleco_ADAM" },
        ["ColecoVision"] = new[] { "Coleco_Vision" },
        ["Commodore 128"] = new[] { "Commodore_128" },
        ["Commodore 64"] = new[] { "Commodore_64" },
        ["Commodore Amiga"] = new[] { "Commodore_Amiga" },
        ["Commodore Amiga CD32"] = new[] { "Commodore_Amiga_CD32" },
        ["Commodore CDTV"] = new[] { "Commodore_CDTV" },
        ["Commodore MAX Machine"] = new[] { "Commodore_MAX_Machine" },
        ["Commodore PET"] = new[] { "Commodore_PET" },
        ["Commodore Plus 4"] = new[] { "Commodore_Plus_4" },
        ["Commodore VIC-20"] = new[] { "Commodore_VIC_20" },
        ["Dragon 32/64"] = new[] { "Dragon_32_64" },
        ["EACA EG2000 Colour Genie"] = new[] { "EACA_EG2000_Colour_Genie" },
        ["Elektronika BK"] = new[] { "Elektronika_BK_0011" },
        ["Emerson Arcadia 2001"] = new[] { "Emerson_Arcadia_2001" },
        ["Entex Adventure Vision"] = new[] { "Entex_Adventure_Vision" },
        ["Epoch Game Pocket Computer"] = new[] { "Epoch_Game_Pocket_Computer" },
        ["Epoch Super Cassette Vision"] = new[] { "Epoch_Super_Cassette_Vision" },
        ["Exelvision EXL 100"] = new[] { "Exelvision_EXL_100" },
        ["Exidy Sorcerer"] = new[] { "Exidy_Sorcerer" },
        ["Fairchild Channel F"] = new[] { "Fairchild_Channel_F" },
        ["Fujitsu FM Towns Marty"] = new[] { "Fujitsu_FM_Towns_Marty" },
        ["Fujitsu FM-7"] = new[] { "Fujitsu_FM_7" },
        ["Funtech Super Acan"] = new[] { "Funtech_Super_Acan" },
        ["GamePark GP32"] = new[] { "Gamepark_GP32" },
        ["GCE Vectrex"] = new[] { "GCE_Vectrex" },
        ["Hartung Game Master"] = new[] { "Hartung_Game_Master" },
        ["Hector HRX"] = new[] { "Hector_HRX" },
        ["Interton VC 4000"] = new[] { "Interton_VC_4000" },
        ["Jupiter Ace"] = new[] { "Jupiter_ACE" },
        ["Magnavox Odyssey"] = new[] { "Magnavox_Odyssey" },
        ["Magnavox Odyssey 2"] = new[] { "Magnavox_Odyssey_2" },
        ["Matra and Hachette Alice"] = new[] { "Matra_and_Hachette_Alice" },
        ["Mattel Aquarius"] = new[] { "Mattel_Aquarius" },
        ["Mattel HyperScan"] = new[] { "Mattel_Hyperscan" },
        ["Mattel Intellivision"] = new[] { "Mattel_Intellivision" },
        ["Mega Duck"] = new[] { "Creatronic_Mega_Duck" },
        ["Memotech MTX512"] = new[] { "Memotech_MTX" },
        ["Microsoft MSX"] = new[] { "Microsoft_MSX" },
        ["Microsoft MSX2"] = new[] { "Microsoft_MSX2" },
        ["Microsoft MSX2+"] = new[] { "Microsoft_MSX2+" },
        ["Microsoft Xbox"] = new[] { "Microsoft_Xbox" },
        ["Microsoft Xbox 360"] = new[] { "Microsoft_Xbox_360" },
        ["Microsoft Xbox One"] = new[] { "Microsoft_Xbox_One" },
        ["Mikrosha"] = new[] { "Radio-86RK_Mikrosha" },
        ["MS-DOS"] = new[] { "Microsoft_MS-DOS" },
        ["MUGEN"] = new[] { "MUGEN" },
        ["Namco System 22"] = new[] { "Namco_System_22" },
        ["NEC PC-8801"] = new[] { "NEC_PC_8801" },
        ["NEC PC-9801"] = new[] { "NEC_PC_9801" },
        ["NEC PC-FX"] = new[] { "NEC_PC_FX" },
        ["NEC TurboGrafx-16"] = new[] { "NEC_TurboGrafx_16" },
        ["NEC TurboGrafx-CD"] = new[] { "NEC_TurboGrafx_CD" },
        ["Nintendo 3DS"] = new[] { "Nintendo_3DS" },
        ["Nintendo 64"] = new[] { "Nintendo_N64" },
        ["Nintendo 64DD"] = new[] { "Nintendo_64DD" },
        ["Nintendo DS"] = new[] { "Nintendo_DS" },
        ["Nintendo Entertainment System"] = new[] { "Nintendo_NES" },
        ["Nintendo Famicom Disk System"] = new[] { "Nintendo_Famicom_Disk_System" },
        ["Nintendo Game & Watch"] = new[] { "_Nintendo_Game_and_Watch" },
        ["Nintendo Game Boy"] = new[] { "Nintendo_Game_Boy" },
        ["Nintendo Game Boy Advance"] = new[] { "Nintendo_Game_Boy_Advance" },
        ["Nintendo Game Boy Color"] = new[] { "Nintendo_Game_Boy_Color" },
        ["Nintendo GameCube"] = new[] { "Nintendo_GameCube" },
        ["Nintendo Pokemon Mini"] = new[] { "Nintendo_Pokemon_Mini" },
        ["Nintendo Satellaview"] = new[] { "Nintendo_Satellaview" },
        ["Nintendo Switch"] = new[] { "Nintendo_Switch" },
        ["Nintendo Virtual Boy"] = new[] { "Nintendo_Virtual_Boy" },
        ["Nintendo Wii"] = new[] { "Nintendo_Wii" },
        ["Nintendo Wii U"] = new[] { "Nintendo_Wii_U" },
        ["Nuon"] = new[] { "VM_Labs_Nuon" },
        ["OpenBOR"] = new[] { "OpenBOR" },
        ["Oric Atmos"] = new[] { "Tangerine_Oric_Atmos" },
        ["Othello Multivision"] = new[] { "_Othello_Multivision" },
        ["PC Engine SuperGrafx"] = new[] { "NEC_SuperGrafx" },
        ["Philips CD-i"] = new[] { "Philips_CD_i" },
        ["Philips VG 5000"] = new[] { "Philips_VG_5000" },
        ["Philips Videopac+"] = new[] { "_Philips_Videopac_" },
        ["Pinball FX2"] = new[] { "Pinball_FX" },
        ["RCA Studio II"] = new[] { "RCA_Studio_II" },
        ["SAM Coupé"] = new[] { "MGT_SAM_Coupé" },
        ["Sammy Atomiswave"] = new[] { "Sammy_Atomiswave" },
        ["ScummVM"] = new[] { "ScummVM" },
        ["Sega 32X"] = new[] { "Sega_32X" },
        ["Sega CD"] = new[] { "Sega_CD" },
        ["Sega Dreamcast"] = new[] { "Sega_Dreamcast" },
        ["Sega Dreamcast VMU"] = new[] { "Sega_Dreamcast_VMU" },
        ["Sega Game Gear"] = new[] { "Sega_Game_Gear" },
        ["Sega Genesis"] = new[] { "Sega_Genesis" },
        ["Sega Hikaru"] = new[] { "Sega_Hikaru" },
        ["Sega Master System"] = new[] { "Sega_Master_System" },
        ["Sega Model 2"] = new[] { "Sega_Model_2" },
        ["Sega Model 3"] = new[] { "Sega_Model_3" },
        ["Sega Naomi"] = new[] { "Sega_Naomi" },
        ["Sega Naomi 2"] = new[] { "Sega_Naomi_2" },
        ["Sega Pico"] = new[] { "Sega_Pico" },
        ["Sega Saturn"] = new[] { "Sega_Saturn" },
        ["Sega SC-3000"] = new[] { "Sega_SC_3000" },
        ["Sega SG-1000"] = new[] { "Sega_SG_1000" },
        ["Sega ST-V"] = new[] { "_Sega_ST_V" },
        ["Sega Triforce"] = new[] { "Sega_Triforce" },
        ["Sharp MZ-2500"] = new[] { "Sharp_MZ_2500" },
        ["Sharp X1"] = new[] { "Sharp_X1" },
        ["Sharp X68000"] = new[] { "Sharp_X68000" },
        ["Sinclair ZX Spectrum"] = new[] { "Sinclair_ZX_Spectrum" },
        ["Sinclair ZX-81"] = new[] { "Sinclair_ZX81" },
        ["SNK Neo Geo AES"] = new[] { "SNK_Neo_Geo_AES" },
        ["SNK Neo Geo CD"] = new[] { "SNK_Neo_Geo_CD" },
        ["SNK Neo Geo MVS"] = new[] { "SNK_Neo_Geo_MVS" },
        ["SNK Neo Geo Pocket"] = new[] { "SNK_Neo_Geo_Pocket" },
        ["SNK Neo Geo Pocket Color"] = new[] { "SNK_Neo_Geo_Pocket_Color" },
        ["Sony Playstation"] = new[] { "Sony_Playstation" },
        ["Sony Playstation 2"] = new[] { "Sony_PlayStation_2" },
        ["Sony Playstation 3"] = new[] { "Sony_PlayStation_3" },
        ["Sony Playstation 4"] = new[] { "Sony_PlayStation_4" },
        ["Sony Playstation 5"] = new[] { "Sony_Playstation_5" },
        ["Sony Playstation Vita"] = new[] { "Sony_PlayStation_Vita" },
        ["Sony PocketStation"] = new[] { "Sony_PocketStation" },
        ["Sony PSP"] = new[] { "Sony_PSP" },
        ["Sony PSP Minis"] = new[] { "Sony_PSP_Minis" },
        ["Sord M5"] = new[] { "Sord_M5" },
        ["Spectravideo"] = new[] { "Spectravideo" },
        ["Super Game Boy"] = new[] { "Nintendo_Super_Gameboy" },
        ["Super Nintendo Entertainment System"] = new[] { "Nintendo_SNES", "_Nintendo_Super_Famicom" },
        ["Super Nintendo MSU-1"] = new[] { "Nintendo_MSU_1" },
        ["Taito Type X"] = new[] { "#_Taito_Type_X" },
        ["Tandy TRS-80"] = new[] { "Tandy_TRS_80" },
        ["TeknoParrot"] = new[] { "ArcadePC" },
        ["Texas Instruments TI 99/4A"] = new[] { "Texas_Instruments_TI_99_4A" },
        ["Tiger Game.com"] = new[] { "Tiger_Game_com" },
        ["Tomy Tutor"] = new[] { "Tomy_Tutor" },
        ["TRS-80 Color Computer"] = new[] { "Tandy_TRS_80_Color_Computer" },
        ["Vector-06C"] = new[] { "Vector_06C" },
        ["Visual Pinball"] = new[] { "Visual_Pinball" },
        ["VTech CreatiVision"] = new[] { "VTech_CreatiVision" },
        ["VTech Socrates"] = new[] { "Vtech_Socrates" },
        ["Watara Supervision"] = new[] { "Watara_Supervision" },
        ["Windows"] = new[] { "Microsoft_Windows" },
        ["Windows 3.X"] = new[] { "Microsoft_Windows_3_x" },
        ["WonderSwan"] = new[] { "Bandai_WonderSwan" },
        ["WonderSwan Color"] = new[] { "Bandai_WonderSwan_Color" },
        ["WoW Action Max"] = new[] { "WoW_Action_Max" },
        ["Z-Machine"] = new[] { "Infocom_Z-Machine" },
    };

    /// <summary>EmuMovies MediaType → LaunchBox image/video type. Value null ⇒ skip that type.</summary>
    public static readonly IReadOnlyDictionary<string, string?> LbType = new Dictionary<string, string?>(StringComparer.OrdinalIgnoreCase)
    {
        ["Snap"] = "Screenshot - Gameplay",
        ["Title"] = "Screenshot - Game Title",
        ["Box"] = "Box - Front",
        ["BoxBack"] = "Box - Back",
        ["Box_3D"] = "Box - 3D",
        ["Box_Full"] = "Box - Full",
        ["Box_25D"] = "Box - Front",
        ["Box_Spine"] = "Box - Spine",
        ["Cart"] = "Cart - Front",
        ["Cart_3D"] = "Cart - 3D",
        ["CartTop"] = "Cart - Top",
        ["Marquee"] = "Arcade - Marquee",
        ["Cabinet"] = "Arcade - Cabinet",
        ["Background"] = "Fanart - Background",
        ["Banner"] = "Banner",
        ["Logos"] = "Clear Logo",
        ["Disc"] = "Disc",
        ["Advert"] = "Advertisement Flyer - Front",
        ["CD"] = "Disc",
        ["Controls"] = "Arcade - Controls Information",
        ["GameOver"] = "Screenshot - Game Over",
        ["PCB"] = "Arcade - Circuit Board",
        ["Music"] = "Music",
        ["Manual"] = "Manual",
        ["Video_MP4"] = "Video",
        ["Video_Database_MP4"] = "Video",
        ["Video_MP4_HD"] = "Video",
        ["Video_MP4_HI_QUAL"] = "Video",
        ["Video_Advert_MP4"] = "VideoAdvert",
        ["Video_MP4_Title"] = null,
        ["Video_MP4_HQ_43"] = null,
        ["Video_Review_MP4"] = null,
        ["Video_Themes_MP4"] = null,
        ["Video_Themes_Wide_MP4"] = null,
        ["Video_System_Intro_MP4"] = null,
        ["Video_System_Intro_WaterMarked"] = null,
        ["Video_Platforms_MP4"] = null,
        ["Manual_CBZ"] = null,
    };

    /// <summary>Parenthetical tag → LaunchBox region. Tags absent here (language/version codes) are
    /// ignored; a name with no known region tag resolves to World.</summary>
    public static readonly IReadOnlyDictionary<string, string> Region = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase)
    {
        ["USA"] = "North America",
        ["US"] = "North America",
        ["United States"] = "North America",
        ["U"] = "North America",
        ["NTSC"] = "North America",
        ["North America"] = "North America",
        ["North American"] = "North America",
        ["Usa"] = "North America",
        ["usa"] = "North America",
        ["Made in USA"] = "North America",
        ["Made in U.S.A."] = "North America",
        ["Japan"] = "Japan",
        ["JPN"] = "Japan",
        ["JP"] = "Japan",
        ["NTSC-J"] = "Japan",
        ["japan"] = "Japan",
        ["JApan"] = "Japan",
        ["Japsn"] = "Japan",
        ["Japapn"] = "Japan",
        ["JAP"] = "Japan",
        ["Europe"] = "Europe",
        ["EUR"] = "Europe",
        ["EU"] = "Europe",
        ["E"] = "Europe",
        ["PAL"] = "Europe",
        ["europe"] = "Europe",
        ["Made in EU"] = "Europe",
        ["Made in E.U."] = "Europe",
        ["European Version"] = "Europe",
        ["Belgium"] = "Europe",
        ["Switzerland"] = "Europe",
        ["Ireland"] = "Europe",
        ["Croatia"] = "Europe",
        ["Slovakia"] = "Europe",
        ["Austria"] = "Europe",
        ["AT"] = "Europe",
        ["Czech Republic"] = "Europe",
        ["CZ"] = "Europe",
        ["Hungary"] = "Europe",
        ["HU"] = "Europe",
        ["Ukraine"] = "Europe",
        ["UA"] = "Europe",
        ["Turkey"] = "Turkey",
        ["TR"] = "Turkey",
        ["World"] = "World",
        ["WLD"] = "World",
        ["JUE"] = "World",
        ["UEJ"] = "World",
        ["UJE"] = "World",
        ["JU"] = "World",
        ["UE"] = "World",
        ["EUJ"] = "World",
        ["NTSC-PAL"] = "World",
        ["PAL-NTSC"] = "World",
        ["jue"] = "World",
        ["Wolrd"] = "World",
        ["France"] = "France",
        ["FR"] = "France",
        ["Germany"] = "Germany",
        ["DE"] = "Germany",
        ["Spain"] = "Spain",
        ["ES"] = "Spain",
        ["SP"] = "Spain",
        ["Italy"] = "Italy",
        ["IT"] = "Italy",
        ["Netherlands"] = "The Netherlands",
        ["NL"] = "The Netherlands",
        ["Brazil"] = "Brazil",
        ["BR"] = "Brazil",
        ["Portugal"] = "Portugal",
        ["PT"] = "Portugal",
        ["Australia"] = "Australia",
        ["AUS"] = "Australia",
        ["Korea"] = "Korea",
        ["KOR"] = "Korea",
        ["KR"] = "Korea",
        ["China"] = "China",
        ["CHN"] = "China",
        ["Asia"] = "Asia",
        ["Taiwan"] = "Asia",
        ["Hong Kong"] = "Hong Kong",
        ["HK"] = "Hong Kong",
        ["Scandinavia"] = "Scandinavia",
        ["Sweden"] = "Sweden",
        ["SE"] = "Sweden",
        ["Canada"] = "Canada",
        ["CA"] = "Canada",
        ["Mexico"] = "Mexico",
        ["MX"] = "Mexico",
        ["Russia"] = "Russia",
        ["UK"] = "United Kingdom",
        ["United Kingdom"] = "United Kingdom",
        ["Finland"] = "Finland",
        ["FI"] = "Finland",
        ["Norway"] = "Norway",
        ["NO"] = "Norway",
        ["Greece"] = "Greece",
        ["GR"] = "Greece",
        ["Latin America"] = "South America",
        ["Argentina"] = "South America",
        ["New Zealand"] = "Oceania",
    };

    /// <summary>Media types that are per-PLATFORM, not per-game — never a game asset.</summary>
    public static readonly HashSet<string> SystemOnly = new(StringComparer.OrdinalIgnoreCase)
    {
        "Background_System",
        "System_Logo",
        "Pointer_System",
        "Marquee_System",
        "Video_System_Intro_MP4",
        "Video_System_Intro_WaterMarked",
        "Video_Platforms_MP4",
    };

    /// <summary>Preferred gameplay-video EmuMovies types, best first.</summary>
    public static readonly string[] VideoPriority = { "Video_MP4", "Video_Database_MP4", "Video_MP4_HD", "Video_MP4_HI_QUAL" };
}
