// Generates dummy implementations of the LaunchBox plugin SDK service/data
// interfaces by reflecting over Unbroken.LaunchBox.Plugins.dll.
//
// Run:   dotnet run --project LbApiHost -- --gen-stubs
// Output: Generated/Dummies.g.cs (one `Dummy<Name>` class per interface).
//
// Strategy:
//   • Target = every interface in namespace Unbroken.LaunchBox.Plugins.Data
//     (plus IRetroAchievementsApi), EXCLUDING the *Plugin interfaces (those
//     are implemented BY plugins, the host only consumes them).
//   • Properties  -> public auto-properties { get; set; } (real storage, so a
//     fake catalog can populate them; a get-only interface prop is satisfied
//     by adding a setter).
//   • Methods     -> return a benign dummy: a fresh Dummy instance when the
//     return type is one of our interfaces, an empty array/list for
//     collections, else default. void methods are no-ops for now (PlayGame &
//     friends get a MessageBox later).
//
// Everything is emitted with global:: fully-qualified type names so there are
// no using/ambiguity problems. Regenerate after an LB SDK update by deleting
// the output file and re-running.

using System.IO;
using System.Linq;
using System.Reflection;
using System.Runtime.Loader;
using System.Text;

namespace LbApiHost.Tools;

internal static class StubGen
{
    private static readonly string[] ProbeDirs =
    {
        @"C:\Users\mehdi\source\repos\scrapper-project\LB\Core",
        @"C:\Users\mehdi\source\repos\scrapper-project\LB\ThirdParty\Chromium",
    };

    public static int Run(string outPath)
    {
        AssemblyLoadContext.Default.Resolving += (ctx, name) =>
        {
            foreach (var dir in ProbeDirs)
            {
                var p = Path.Combine(dir, name.Name + ".dll");
                if (File.Exists(p)) { try { return ctx.LoadFromAssemblyPath(p); } catch { } }
            }
            return null;
        };

        var asm = typeof(Unbroken.LaunchBox.Plugins.PluginHelper).Assembly;
        Type[] types;
        try { types = asm.GetExportedTypes(); }
        catch (ReflectionTypeLoadException ex) { types = ex.Types.Where(t => t != null).ToArray(); }

        var targets = types.Where(t => t.IsInterface
                && (t.Namespace == "Unbroken.LaunchBox.Plugins.Data"
                    || t.FullName == "Unbroken.LaunchBox.Plugins.RetroAchievements.IRetroAchievementsApi")
                && !t.Name.EndsWith("Plugin"))
            .OrderBy(t => t.Name)
            .ToList();

        var targetSet = new HashSet<Type>(targets);
        var dummyName = new Dictionary<Type, string>();
        foreach (var t in targets)
            dummyName[t] = "Dummy" + (t.Name.StartsWith("I") ? t.Name.Substring(1) : t.Name);

        var sb = new StringBuilder();
        sb.AppendLine("// <auto-generated/> Dummy implementations of the LaunchBox plugin SDK.");
        sb.AppendLine("// Regenerate: delete this file, then `dotnet run --project LbApiHost -- --gen-stubs`.");
        sb.AppendLine("#pragma warning disable");
        sb.AppendLine("namespace LbApiHost.Generated");
        sb.AppendLine("{");
        foreach (var t in targets)
            EmitClass(sb, t, dummyName, targetSet);
        sb.AppendLine("}");

        Directory.CreateDirectory(Path.GetDirectoryName(outPath));
        File.WriteAllText(outPath, sb.ToString());

        Console.WriteLine($"Generated {targets.Count} dummy classes -> {outPath}");
        foreach (var t in targets) Console.WriteLine("  " + dummyName[t] + " : " + t.FullName);
        return 0;
    }

    private static void EmitClass(StringBuilder sb, Type iface, Dictionary<Type, string> dummyName, HashSet<Type> targetSet)
    {
        // partial + virtual so a hand-written Host{X} subclass (or partial) can
        // specialize the few members that need real dummy behavior (fake
        // catalog, MessageBox launch) without fighting regeneration.
        sb.AppendLine($"  public partial class {dummyName[iface]} : {TypeRef(iface)}");
        sb.AppendLine("  {");

        // Members from the interface AND all its base interfaces, deduped.
        var all = new List<Type> { iface };
        all.AddRange(iface.GetInterfaces());

        foreach (var p in all.SelectMany(i => i.GetProperties()).GroupBy(p => p.Name).Select(g => g.First()))
            sb.AppendLine($"    public virtual {TypeRef(p.PropertyType)} {p.Name} {{ get; set; }}");

        foreach (var m in all.SelectMany(i => i.GetMethods())
                             .Where(m => !m.IsSpecialName)
                             .GroupBy(Sig).Select(g => g.First()))
        {
            var ps = string.Join(", ", m.GetParameters().Select(pp => $"{ParamRef(pp)} {Ident(pp.Name)}"));
            sb.AppendLine($"    public virtual {TypeRef(m.ReturnType)} {m.Name}({ps}) {{ {Body(m, dummyName, targetSet)} }}");
        }

        sb.AppendLine("  }");
    }

    private static string Sig(MethodInfo m) =>
        m.Name + "|" + string.Join(",", m.GetParameters().Select(p => p.ParameterType.FullName ?? p.ParameterType.Name));

    private static string Body(MethodInfo m, Dictionary<Type, string> dummyName, HashSet<Type> targetSet)
    {
        var outs = string.Concat(m.GetParameters()
            .Where(p => p.ParameterType.IsByRef && p.IsOut)
            .Select(p => $"{Ident(p.Name)} = default; "));

        var ret = m.ReturnType;
        if (ret == typeof(void)) return outs.Trim();

        string expr;
        if (targetSet.Contains(ret))
            expr = $"return new {dummyName[ret]}();";
        else if (ret.IsArray)
            expr = $"return global::System.Array.Empty<{TypeRef(ret.GetElementType())}>();";
        else if (ret.IsGenericType && IsListLike(ret.GetGenericTypeDefinition()))
            expr = $"return new global::System.Collections.Generic.List<{TypeRef(ret.GetGenericArguments()[0])}>();";
        else if (ret.IsGenericType && IsDictLike(ret.GetGenericTypeDefinition()))
            expr = $"return new global::System.Collections.Generic.Dictionary<{TypeRef(ret.GetGenericArguments()[0])}, {TypeRef(ret.GetGenericArguments()[1])}>();";
        else
            expr = "return default;";

        return (outs + expr).Trim();
    }

    private static bool IsListLike(Type gd) =>
        gd == typeof(System.Collections.Generic.List<>) ||
        gd == typeof(System.Collections.Generic.IList<>) ||
        gd == typeof(System.Collections.Generic.ICollection<>) ||
        gd == typeof(System.Collections.Generic.IEnumerable<>) ||
        gd == typeof(System.Collections.Generic.IReadOnlyList<>) ||
        gd == typeof(System.Collections.Generic.IReadOnlyCollection<>);

    private static bool IsDictLike(Type gd) =>
        gd == typeof(System.Collections.Generic.Dictionary<,>) ||
        gd == typeof(System.Collections.Generic.IDictionary<,>) ||
        gd == typeof(System.Collections.Generic.IReadOnlyDictionary<,>);

    private static string ParamRef(ParameterInfo p)
    {
        var t = p.ParameterType;
        if (t.IsByRef) return (p.IsOut ? "out " : "ref ") + TypeRef(t.GetElementType());
        return TypeRef(t);
    }

    private static string TypeRef(Type t)
    {
        if (t == typeof(void)) return "void";
        if (t.IsByRef) return TypeRef(t.GetElementType());
        if (t.IsArray) return TypeRef(t.GetElementType()) + "[]";
        if (t.IsGenericParameter) return t.Name;

        if (t.IsGenericType)
        {
            var gd = t.GetGenericTypeDefinition();
            string nm = gd.Name;
            int bt = nm.IndexOf('`');
            if (bt >= 0) nm = nm.Substring(0, bt);
            string full = (string.IsNullOrEmpty(gd.Namespace) ? nm : gd.Namespace + "." + nm).Replace("+", ".");
            string args = string.Join(", ", t.GetGenericArguments().Select(TypeRef));
            return $"global::{full}<{args}>";
        }

        string fn = t.FullName;
        if (string.IsNullOrEmpty(fn)) fn = string.IsNullOrEmpty(t.Namespace) ? t.Name : t.Namespace + "." + t.Name;
        return "global::" + fn.Replace("+", ".");
    }

    private static string Ident(string name)
    {
        if (string.IsNullOrEmpty(name)) return "arg";
        return Keywords.Contains(name) ? "@" + name : name;
    }

    private static readonly HashSet<string> Keywords = new()
    {
        "object","string","int","bool","class","event","params","ref","out","in","base","this","default","void","lock","null","new"
    };
}
